### ISSUE TITLE
Add this to the Arduino library manager

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/UC121902-TNARX-A#3]
As of Pull Request #2, this seems to be compliant with the needed layout.
Please add this library to the Arduino Library manager, so people can find it more easily.
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by per1234** [comment]
A couple of things need to be done to get the library in the Arduino Library Manager index:

1. Update the [`version` value in library.properties](https://github.com/niccokunzmann/UC121902-TNARX-A/blob/master/library.properties#L2) to the version number you want to use for the next release. This should be a higher version number than the previous[ 0.1 release](https://github.com/niccokunzmann/UC121902-TNARX-A/releases/tag/0.1).
2. Create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.
3. Open an issue report at https://github.com/arduino/Arduino/issues with this repository's URL, requesting inclusion in the Arduino Library Manager index.

It will take a few days for an Arduino employee to add the URL to the Library Manager indexer job. After that, any new releases you make will automatically be picked up by the indexer. The Arduino IDE displays an updatable library notification to any user who has the library installed and they can update to the new version with only a few clicks.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by niccokunzmann** [comment]
- #5 updates the version number to 1.0
- a [tag 1.0](https://github.com/niccokunzmann/UC121902-TNARX-A/releases/tag/1.0) is created

**Comment by niccokunzmann** [comment]
@per1234 Would you be interested to get commits rights?

**Comment by per1234** [comment]
Sure, if you like. After a quick look I do see one minor fix I can make to library.properties and I can do #4 if you like. Of course I could also just submit PRs for those if you prefer.

**Comment by niccokunzmann** [comment]
@per1234 You are invited to contribute: https://github.com/niccokunzmann/UC121902-TNARX-A/invitations
You can do those issues I added but you can also ignore them - as you like. I added you so there is one more maintainer for this in case other people come here and want to do changes. I mean in a sense that you do not have to do anything but I trust your judgment on the library and you have the ability to change it, now.

**Comment by per1234** [comment]
OK, thanks! I'm happy to help with administration of the repository. I do that on the arduino/Arduino repository as well as a couple others and I think I've been able to be helpful in that capacity.

**Comment by niccokunzmann** [comment]
This can be closed as it was added to the library manager.
